### PR TITLE
remove man page as documentation

### PR DESCRIPTION
**Pull request by ousia**
@juhp, would it be possible to include this patch to have the man page of pandoc.

I cannot test it myself, but I think it should work.

### CODE REVIEW

**Comment by juhp** [comment]
Ah you want to treat it as a normal manpage.

I should have added a comment probably:
so actually this is a intentional to allow the pandoc package is coexist with pandoc-common in Fedora. Maybe I should put it into pandoc-docs instead or something.  Though I agree having it all in one package is easier.  Maybe users prefer just to remove pandoc-common in practice...

**Comment by juhp** [comment]
A few more comments:
- actually the Fedora packaging is probably over-complicated
  - I introduced the Fedora static subpackage a while back to allow it not to depend on ghc version but maybe now with copr it is not longer needed so much: the copr packages are Haskell static and embedded anyway (the later basically because cabal sandbox doesn't work well for data files...).
- a simple workaround for now (which I did today for cabal-install) would be to require pandoc-common which would pull in the Fedora manpage (though also all the data files which would be redundant)
  - however the common manpage would not be 100% up to date but better than nothing (hence why I was including the current manpage file as a doc file so one could open it by hand with man)

**Comment by ousia** [comment]
I’m afraid I don’t see the gain in having pandoc-common besides the latest pandoc stable.

**Comment by juhp** [comment]
Right - I think I will drop pandoc-common and pandoc-static soon in Fedora, then this problem will go away.

**Comment by juhp** [comment]
Hummpf, I forgot that ghc-pandoc also requires pandoc-common...
Maybe the best I can do currently is to move the manpage from common to the main Fedora package.  I think that is the only file that conflicts.  Until then I fear I need to revert your change.

**Comment by juhp** [comment]
One other short-term possibility: rename the manpage file to pandoc-%{version} for now until I sort out the Fedora side which may well take some time.

**Pull request merged**
